// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itssmqdjptzjueetjbql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0c3NtcWRqcHR6anVlZXRqYnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDY2ODgsImV4cCI6MjA1ODkyMjY4OH0.qVmwQagaf71abh8aUyxXq5DAz1r4wCzVqiAqVPfZawY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);